### ISSUE TITLE
Craft 5 Compatability

### ISSUE THREAD

**Issue by terryupton** [croxton/imgixer#14]
Hey @croxton 
Hope you are doing well.
Just wanted to check that this plugin will be upgraded for Craft 5 and if you had any timeframes around this? 
Thanks.

**Comment by croxton** [comment]
Yes, it definitely will! I'm hoping to get on to it very soon.

**Comment by terryupton** [comment]
Hey @croxton - not to add any pressure and be demanding; but just wondered if you had an ETA on this being ready for Craft 5? I have a project I am 15% into that I would like to migrate (or restart) in Craft 5 and it currently uses this plugin. I can probably disable it and do local transforms for not; but thought I would ask the question.

**Comment by croxton** [comment]
Hey @terryupton sorry I've just been tied up with project work -- I'll take a look this weekend coming. This plugin makes very little demands on Craft itself so my guess is it should be a straightforward upgrade.

**Comment by terryupton** [comment]
No worries @croxton. Fully appreciate the demands of project work 😉
Brilliant! Thanks for getting back to me 👍🏻

**Comment by croxton** [comment]
I tagged a release for Craft 5 - everything seems to be working but I haven't had time to fully test Servd with the v3 Asset platform (the Servd plugin for Craft 5 has evolved quite a bit so there might be gremlins there). Also the Imagekit API has had some subtle changes recently (I updated the library for that too) - which I still need to test.

https://github.com/croxton/imgixer/releases/tag/3.0.0-beta.1

**Comment by terryupton** [comment]
Thanks @croxton - installed and all working on initial inspection. I am working through a Craft 5 build so I will report any issues if any crop up. Thanks again for sorting this 👍🏻
