### ISSUE TITLE
Signed token?

### ISSUE THREAD

**Issue by rpickering** [croxton/imgixer#18]
Possibly a stupid question... how would I pass through Imgix's 'signed token'?

I'm migrating from an old plugin, and I can't see an example of it in the config.

My imgix URLs are returning 'sig_invalid'

Thanks!

**Comment by croxton** [comment]
Hi Rory, you would pass the token in the `privateKey` setting for your source, e.g.:

```php
<?php
return [
    'sources' => array(
        'mySource' => array(
            'provider' => 'imgix',
            'endpoint'   => 'my-domain.imgix.net',
            'privateKey'   => 'token-goes-here',
            'signed'    => true,
            'defaultParams' => array(
                'auto' => 'compress,format',
                'fit' => 'crop'
            )
        )
    ),
];
```

You might also want to make the token an environmental variable so it's not hardcoded in the config file, e.g.: 

```
'privateKey'   => getenv('IMGIX_TOKEN')
```

**Comment by rpickering** [comment]
Thanks for responding. In that case then, where would the API key go? As I had understood privateKey was for that rather than the token, and the plugin I used before sent both.

Again apologies if I have misunderstood this!

**Comment by rpickering** [comment]
Here's the config for my old plugin (keys/tokens removed):

```
return [
    // Imgix API key
    'apiKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

    // Imgix signed URLs token
    'imgixSignedToken' => 'xxxxxxxxxxxxxxxx',

    // Volume handles mapped to Imgix domains
    'imgixDomains' => [
        'images' => 'xxxxxxxxxx.imgix.net'
    ],
];
```

**Comment by croxton** [comment]
Imgixer doesn't use Imgix's API key.

Your old plugin probably used it to ping Imgix to purge the cache, but Imgixer doesn't do that - this is a deliberate design choice, not an omission. See https://github.com/croxton/imgixer?tab=readme-ov-file#asset-purging

**Comment by rpickering** [comment]
Got it! Thanks for clarification
